### ISSUE TITLE
Usability Improvements

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/avalon#23]
- [ ] Fields which are not accessible should not be displayed on the collection page (?)
- [ ] Manage file(s) use upload file text (?)
- [ ] Skip transcode is not used commonly, should be removed (?)
- [ ] Change the title Upload another file (?)
- [x] Grey color is not too grey (?)
- [ ] Display proper error messages (?)
- [ ] Breadcrumbs on the top would help (?)
- [ ] Leftside menu should better be handled (?)
- [ ] Save and continue to “which step” (?)
- [ ] Remove view raw metadata option (?)

**Comment by seanluyk** [comment]
I've created separate issues for a number of issues in this mega-issue. What's left requires some more discussion at our grooming meeting - I'm not sure what they mean/where they are referring to.

**Comment by seanluyk** [comment]
@umarqasim  - flagging this for us to work on at our next grooming meeting - need to create separate issues

**Comment by seanluyk** [comment]
Doing some cleanup
