### ISSUE TITLE
ERA-AV Avalon 6 Upgrade

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/avalon#265]
### Descriptive summary

This is an epic issue to capture the work required for the Avalon 6 upgrade for the ERA-AV repository. 
Latest version:
https://github.com/avalonmediasystem/avalon/tree/v6.2.0

### Requirements:
- [ ] Deposit form changes ported over
- [ ] LTI integration related changed ported over
- [ ] Batch ingest functionality
- [ ] Data validation customization
- [ ] UI design ported over
- [ ] Data migration
- [ ] Accessibility scan and fixes

**Comment by seanluyk** [comment]
Doing some cleanup
