### ISSUE TITLE
Avalon 6: Port local U of A features

### ISSUE THREAD

**Issue by cwant** [ualbertalib/avalon#282]
Will need to break these into separate issues, but will also need to determine which of these are still needed:

 - [x] Configure for wowza streaming
   - [ ] Adding gem: e47a7d203db17431e911826634ec447c1af7772c
   - [x] ~~Streaming token fixes: f16e0526fe50da84dc5e7b8b6586d4eecea80257 637ccb7648429be1e873fa51d9efa16077aa846a~~ (Seems to have been an issue upgrading to Rails 4.1 a while back)
 - [x] Authentication
   - [ ] Initial commit: 0e1068c05ad26828f89c6a1795576b173c4baf16
   - [ ] Login and branding: e86bf82b73ef595aa1c9e92b4831bd176b82eabe
   - [ ] Shib and email: 30d83fc5c80c17d7eeb110309069469637e12ba7
   - [ ] Email as `User.username`: b6cd19d2188fd8977279db0c68ad825ccb7b02e5
   - [ ] More shib: a21578b570c2c7b49703a931d3178c301bb28b22
 - [ ] LTI / eClass:
   - [x] **Instructor embed custom params (in review)**
        Previous 7d784884f5649b69b29a26a90679603532347237, Current #325, PR #327
   - [x] **Relabel to eClass (in review)**
        Previous #66, Current #325, PR #327
   - [x] ~~Missing scrollbars #246 (seems to be fixed in eClass?)~~
   - [x] **Fix auth token (rollbar 'thousand errors a day' issue) (in review)**
       Previous #278, Current #325, PR #327
 - [x] ~~Forked `modal_logic` gem:~~ Don't need
   - [x] ~~Gem added: 2d6511c5eb719058b4a8324ccb62d2bbcf1590c2~~
   - [x] ~~`multipart-post` gem: 533378a9a1ae8e5d7de3d19cc7169c9b4fad2768~~
 - [ ] Monkeypatch ActionDispatch for `stringify_key`: 5bbbbc931ce7cb73df6f9a7dfccbce0cae13188a
 - [x] Metadata changes (Epic #290):
   - [x] **Mandatory metadata and UI: 86049f38d8ed1375561151106e2ad120fea9fdf5 (in review)**
         Current Issues: #291, #292, PR: #302 
   - [x] Deposit checkbox and license stuff: 3c3dfa03d363ccb87fca511ddc3642968e0d16d0
   - [ ] Batch ingest / License stuff: bf12466fbf5282c0f45f396f329e85913d9be82f
   - [ ] Factory validations: 78d03f2a4b8f5141cd9750cd3a8315fa2d6eba83
   - [x] **Genre requires/PBCore (in review)**
         Previous Issue #57, Current Issue #293, PR: #302
   - [x] **Form: required fields/help (in review)**
         Previous Issues #7 #94, Current Issue #295, PR: #296 
   - [x] **'Archival Identifier' (in review)**
         Previous #83, Current #314, PR #315
   - [x] ~~Genre after subject: #138~~ This is in PR #302 
 - [x] Static pages: 1ce628a73f0a1789ea445e63af1e3b8bd8403819
 - [ ] Google analytics
       Previous: 17c07db4d7994ede3392ff7820e8e4955879f942, Current: #318, PR #319 
 - [ ] Batch ingest:
   - [ ] Error handling: 355528cf64a4d42e6270f4db0850a5d04198438e
   - [ ] Test suite: b8087213acb7304dc6a1bd7fc67efafa30c540f3 7819be42f27d7ea125d3882327c8be07be93f522 bb7b49b0c3844fa8b5e1a63edcf805a369d30f5e
   - [ ] Batch update:
       Previous: #80, Current: #337 
   - [x] ~~Batch ingest button~~ (Not needed)
       Previous #56, Current #336  
   - [x] **Dropbox group write permissions (in review)**
      Previous #168 #170, Current #322, PR: #323 
   - [x] CC errors mailing list on ingest
       Previous #163, Current: #338, PR #346 
   - [x] Deprecation warnings #137 
 - [x] Player:
    - [x] Autohide controls (needed?) #55 
    - [x] Opacity on Safari (needed?)#252
 - [x] ~~Travis: #122 #234 #279 (<-- likely not needed)~~ Travis already works
 - [x] Frontend theme: #165 #183 4eb4a009dbbb80428f169f53a3f334e660554bb3 24bc7d9bb601c1b3afacb6314f05ee888f89424f e34210ec46b63abfa4df66ad5c140908afb6da4e
 - [ ] Other:
   - [ ] Add zoom: 35ae64bf72e27b486abb474480ca2f3fcbf9e11f
   - [ ] Open related URLs in other tab: 2cb8eef23ddde799e3f867413b8b7a32fcd9c4c3 -- this will be mixed with the license display code from #294. *
   - [ ] Script to dump datastreams: 6146e7230ee5601422d0654f2f2f433da0ef05cb
   - [x] ~~Preventing deprecation warnings from filling logs: #53~~ Supposed to be fixed in Avalon 6
   - [x] **Remove Unit from facets (in review)**
         Previous: #17, Current: #305, PR: #309
   - [x] Facet test wrapping (likely not needed): 7e909c9829ccd6a2d031dc3dbb69940ea0ff7bd0
   - [ ] Blacklight helper reload issues (likely not needed): 3add74ff6a7d9c9a8e41573b589add38e09a1b67 c582eae1c973cc9318b544e04115d668de4c3a6a
   - [ ] Bibliographic import: #13 #110 
   - [ ] Test suite issues: #101 
   - [ ] `Avalon::Batch::Entry#valid?` fix (I think is in upstream): 8a00cb7c8e81959f7c49eb7831a91a24d0de0d21 dc23a26376fe7c32c32471fcdf1f61a690e8e05c
   - [x] **Share button more noticeable (in review)**
         Previous #50, Current #303, PR: #304  
   - [x] **Add staging environment (in review)**
         Previous #157, Current #312, PR #313 
   - [x] **Rollbar (in review)**
         Previous #152, Current #316, PR #317 
   - [ ] Block Yandex #171 
   - [ ] **Allow editors to unpublish via button (in review)**
        Previous: #60 #61 #185, Current: #340, PR: #352 
   - [ ] **Invalid object report (in review)**
       Previous: #162, Current:  #339; PR #350 
   - [ ] Test suite clobbers config (likely sent upstream) 6fa287363479cc414ca084a57125d1ebe4a9a500
   - [ ] Crash deleting objects with bad workflow #213

**Comment by weiweishi** [comment]
@seanluyk I believe we can close this ticket now? Other feature enhancement will be its own GitHub issue, and not part of the 5->6 migration? Please reopen if you think otherwise.
