### ISSUE TITLE
Avalon 6: Metadata features epic

### ISSUE THREAD

**Issue by cwant** [ualbertalib/avalon#290]
This epic is to track the work for porting the local changes of metadata to Avalon 6.

 - [ ] #295 Form: required fields/help #7 #94 
 - [ ] #291 Make subject Mandatory: 86049f38d8ed1375561151106e2ad120fea9fdf5 78d03f2
 - [ ] #292 Make language Mandatory: 86049f38d8ed1375561151106e2ad120fea9fdf5 78d03f2
 - [ ] #293 Genre required/PBCore: #57 
 - [ ] #294 Spike: Revisit Language and Access Rights: 86049f38d8ed1375561151106e2ad120fea9fdf5
 - [ ] Deposit checkbox and license stuff: 3c3dfa03d363ccb87fca511ddc3642968e0d16d0
 - [ ] Batch ingest / License stuff: bf12466fbf5282c0f45f396f329e85913d9be82f
 - [ ] 'Archival Identifier' #83
 - [ ] Genre after subject: #138

**Comment by weiweishi** [comment]
@seanluyk I believe we can close this ticket now? Other metadata enhancement will be its own github issue, and not part of the 5->6 migration? Please reopen if you think otherwise.
