### ISSUE TITLE
[Avalon] Debugging batch ingest in Avalon 6

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/avalon#530]
### Descriptive summary

It's reported that batch ingest functionality is not working in avalon 6. Some investigation work:

- [x] Cron job and the automated process of batch ingest job: @jefferya found [the documentation](https://wiki.dlib.indiana.edu/display/VarVideo/Manual+Installation+Instructions#ManualInstallationInstructions-Batchingest) to run the batch ingest from the command-line. The installation instructions mention a cron job that automatically runs at a regular interval to batch ingest automatically. Need to determine if this process is executing correctly or if the cron job is executing. 
    - cron job needs to be added to Prod and Test (example under deploy account) as per: #532 
- [X] Radioactive batch ingest record: https://docs.google.com/spreadsheets/d/1nlvJ475n-waSdqoHdlA3zNnCC7dWro2HR9-YXbhh2YQ/edit?usp=sharing_eil&ts=5d5c4f96
- [x] Email notification for batch ingest job
   - details in #533 
- [x] "processed" flag file, still relevant? 
  - no longer created; appears to be replaced by removing the manifest file [Troubleshooting Batch ingest](https://wiki.dlib.indiana.edu/display/VarVideo/Troubleshooting+a+Batch+Ingest)
- [x] Monitoring of batch ingest job. Matterhorn admin, Resque jobs? What else? #535 
  - [Di Internal Monitoring](https://github.com/ualbertalib/di_internal/blob/master/System-Adminstration/avalon/avalon_documentation.md#logs-monitoring-and-diagnostics)
  - [DI Internal Ingest failures](https://github.com/ualbertalib/di_internal/blob/master/System-Adminstration/avalon/avalon_documentation.md#ingest-failures)
- [x] Batch update functionality in Avalon 6 #534 
  - [Troubleshooting Batch ingest](https://wiki.dlib.indiana.edu/display/VarVideo/Troubleshooting+a+Batch+Ingest)
  - [DI Internal batch ingest](https://github.com/ualbertalib/di_internal/blob/master/System-Adminstration/avalon/avalon_documentation.md#batch-ingest)

**Comment by jefferya** [comment]
Updated DI Internal document <https://github.com/ualbertalib/di_internal/blob/master/System-Adminstration/avalon/avalon_documentation.md#batch-ingest>
